// import { Inter } from "next/font/google";
import { Head, Html, Main, NextScript } from "next/document";
import { ToastContainer } from "react-toastify";

// const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function Document({ children }) {
  return (
    <Html lang="en">
      <Head />
      <body className={"inter.className"}>
        <Main />
        <NextScript />
        <ToastContainer />
      </body>
    </Html>
  );
}
